### PR TITLE
Fix path vulnerability + mkdir update

### PR DESCRIPTION
**Pull request by fullstackfool**
Fixed issue with folder vulnerability in a user provided path + added command to create the specified storage folder if it does not already exist

### CODE REVIEW

**Comment by midnite81** [comment]
Where is your documentation on the readme?!

**Comment by georgehanson** [comment]
Possibly make `flags` an array and move it before the `limit` parameter? Otherwise if I wanted to pass an extra flag, but not limit the results, I would have to pass through a `null` parameter

**Comment by fullstackfool** [comment]
Moved the flags parameter as suggested. Docs in progress

**Comment by fullstackfool** [comment]
Docs still in progress.

**Comment by georgehanson** [comment]
> Docs still in progress.

Never give up.

**Comment by fullstackfool** [comment]
World is not ready for this.

**Comment by midnite81** [comment]
> World is not ready for this.

Five years in the making for this quote @fullstackfool

**Pull request closed without merging**
